// Comprehensive trades and service categories similar to Thumbtack

export interface ServiceCategory {
  id: string;
  name: string;
  subcategories: string[];
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "home-improvement",
    name: "Home Improvement & Repair",
    subcategories: [
      "General Contracting",
      "Remodeling",
      "Kitchen Remodeling",
      "Bathroom Remodeling",
      "Basement Finishing",
      "Home Additions",
      "Deck & Porch Building",
      "Fence Installation & Repair",
      "Drywall Installation & Repair",
      "Framing",
      "Insulation Installation",
      "Window Installation & Repair",
      "Door Installation & Repair",
      "Garage Door Installation & Repair",
      "Siding Installation & Repair",
      "Gutter Installation & Cleaning",
      "Foundation Repair",
      "Waterproofing",
      "Concrete & Masonry",
      "Tile Installation",
      "Hardwood Flooring",
      "Carpet Installation",
      "Laminate & Vinyl Flooring",
      "Countertop Installation",
      "Cabinet Installation",
    ],
  },
  {
    id: "plumbing-hvac-electrical",
    name: "Plumbing, HVAC & Electrical",
    subcategories: [
      "Plumbing Repair & Installation",
      "Drain Cleaning",
      "Water Heater Installation & Repair",
      "Sewer Line Repair",
      "Septic System Service",
      "Sump Pump Installation & Repair",
      "Gas Line Installation & Repair",
      "Backflow Testing",
      "HVAC Installation",
      "Air Conditioning Repair",
      "Heating System Repair",
      "Furnace Repair & Installation",
      "Duct Cleaning",
      "Air Quality Testing",
      "Thermostat Installation",
      "Electrical Repair & Installation",
      "Panel Upgrades",
      "Outlet & Switch Installation",
      "Ceiling Fan Installation",
      "Lighting Installation",
      "Generator Installation",
      "EV Charger Installation",
      "Smart Home Installation",
      "Security System Installation",
    ],
  },
  {
    id: "roofing-exterior",
    name: "Roofing & Exterior",
    subcategories: [
      "Roof Installation",
      "Roof Repair",
      "Roof Inspection",
      "Gutter Installation",
      "Gutter Cleaning",
      "Soffit & Fascia Repair",
      "Chimney Repair & Cleaning",
      "Skylight Installation",
      "Painting (Interior)",
      "Painting (Exterior)",
      "Staining & Sealing",
      "Wallpaper Installation",
      "Power Washing",
      "Window Washing",
      "Exterior Cleaning",
    ],
  },
  {
    id: "landscaping-outdoor",
    name: "Landscaping & Outdoor",
    subcategories: [
      "Lawn Care & Maintenance",
      "Lawn Mowing",
      "Landscape Design",
      "Landscape Installation",
      "Tree Trimming & Removal",
      "Stump Removal",
      "Mulching",
      "Sod Installation",
      "Seeding & Aeration",
      "Irrigation System Installation",
      "Sprinkler Repair",
      "Hardscaping",
      "Patio Installation",
      "Retaining Wall Installation",
      "Outdoor Lighting",
      "Pool Installation",
      "Pool Maintenance",
      "Hot Tub Installation",
      "Outdoor Kitchen Installation",
      "Pergola & Gazebo Installation",
      "Snow Removal",
      "Leaf Removal",
    ],
  },
  {
    id: "cleaning-organization",
    name: "Cleaning & Organization",
    subcategories: [
      "House Cleaning",
      "Deep Cleaning",
      "Move-In/Move-Out Cleaning",
      "Post-Construction Cleaning",
      "Carpet Cleaning",
      "Upholstery Cleaning",
      "Window Cleaning",
      "Pressure Washing",
      "Gutter Cleaning",
      "Organizing & Decluttering",
      "Garage Organization",
      "Closet Organization",
      "Junk Removal",
      "Hoarding Cleanup",
    ],
  },
  {
    id: "pest-control",
    name: "Pest Control & Extermination",
    subcategories: [
      "General Pest Control",
      "Termite Control",
      "Bed Bug Treatment",
      "Rodent Control",
      "Mosquito Control",
      "Ant Control",
      "Wildlife Removal",
      "Bee & Wasp Removal",
    ],
  },
  {
    id: "appliance-repair",
    name: "Appliance Repair & Installation",
    subcategories: [
      "Refrigerator Repair",
      "Washer & Dryer Repair",
      "Dishwasher Repair",
      "Oven & Stove Repair",
      "Microwave Repair",
      "Garbage Disposal Repair",
      "Ice Maker Repair",
      "Appliance Installation",
    ],
  },
  {
    id: "moving-storage",
    name: "Moving & Storage",
    subcategories: [
      "Local Moving",
      "Long Distance Moving",
      "Packing Services",
      "Unpacking Services",
      "Furniture Assembly",
      "Junk Removal",
      "Storage Unit Rental",
      "Piano Moving",
      "Pool Table Moving",
    ],
  },
  {
    id: "automotive",
    name: "Automotive Services",
    subcategories: [
      "Auto Repair",
      "Oil Change",
      "Brake Repair",
      "Transmission Repair",
      "Engine Repair",
      "Auto Detailing",
      "Car Wash",
      "Window Tinting",
      "Dent Repair",
      "Paintless Dent Removal",
      "Auto Body Repair",
      "Tire Services",
      "Wheel Alignment",
      "Muffler Repair",
    ],
  },
  {
    id: "professional-services",
    name: "Professional Services",
    subcategories: [
      "Accounting & Bookkeeping",
      "Tax Preparation",
      "Financial Planning",
      "Legal Services",
      "Real Estate Law",
      "Business Law",
      "Estate Planning",
      "Notary Services",
      "IT Support",
      "Computer Repair",
      "Network Installation",
      "Data Recovery",
      "Website Design",
      "Graphic Design",
      "Marketing & Advertising",
      "Social Media Management",
      "Copywriting",
      "Translation Services",
    ],
  },
  {
    id: "events",
    name: "Events & Entertainment",
    subcategories: [
      "Event Planning",
      "Wedding Planning",
      "Catering",
      "Bartending",
      "Photography",
      "Videography",
      "DJ Services",
      "Live Music",
      "Party Entertainment",
      "Face Painting",
      "Balloon Decoration",
      "Event Rentals",
      "Photo Booth Rental",
      "Tent Rental",
      "Table & Chair Rental",
    ],
  },
  {
    id: "wellness-beauty",
    name: "Wellness & Beauty",
    subcategories: [
      "Personal Training",
      "Yoga Instruction",
      "Nutrition Coaching",
      "Massage Therapy",
      "Physical Therapy",
      "Chiropractic Care",
      "Acupuncture",
      "Mental Health Counseling",
      "Life Coaching",
      "Hair Styling",
      "Makeup Artist",
      "Nail Services",
      "Spa Services",
      "Skin Care",
      "Teeth Whitening",
    ],
  },
  {
    id: "lessons-tutoring",
    name: "Lessons & Tutoring",
    subcategories: [
      "Academic Tutoring",
      "Math Tutoring",
      "Reading & Writing Tutoring",
      "Test Prep (SAT, ACT, GRE)",
      "Music Lessons (Piano)",
      "Music Lessons (Guitar)",
      "Music Lessons (Drums)",
      "Music Lessons (Violin)",
      "Music Lessons (Voice)",
      "Art Lessons",
      "Dance Lessons",
      "Language Lessons",
      "Acting Lessons",
      "Sports Coaching",
      "Swimming Lessons",
      "Driving Lessons",
    ],
  },
  {
    id: "pet-services",
    name: "Pet Services",
    subcategories: [
      "Dog Walking",
      "Pet Sitting",
      "Pet Boarding",
      "Dog Training",
      "Pet Grooming",
      "Veterinary Services",
      "Pet Waste Removal",
      "Aquarium Services",
      "Horse Training",
      "Pet Photography",
    ],
  },
  {
    id: "childcare-senior",
    name: "Childcare & Senior Care",
    subcategories: [
      "Babysitting",
      "Nanny Services",
      "Daycare",
      "After-School Care",
      "Special Needs Care",
      "Senior Care",
      "Companion Care",
      "Home Health Aide",
      "Respite Care",
      "Elderly Transportation",
    ],
  },
  {
    id: "specialty-crafts",
    name: "Specialty & Crafts",
    subcategories: [
      "Locksmith",
      "Upholstery",
      "Furniture Refinishing",
      "Antique Restoration",
      "Woodworking",
      "Custom Carpentry",
      "Metalworking",
      "Welding",
      "Glass Repair",
      "Watch Repair",
      "Jewelry Repair",
      "Shoe Repair",
      "Tailoring & Alterations",
      "Custom Sewing",
    ],
  },
];

// Flatten all subcategories into a single array for easy selection
export const ALL_SERVICE_TYPES = SERVICE_CATEGORIES.flatMap((category) =>
  category.subcategories.map((sub) => ({
    category: category.name,
    service: sub,
    fullName: `${category.name} > ${sub}`,
  }))
);
